// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlyomoppabawqxgtdqni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFseW9tb3BwYWJhd3F4Z3RkcW5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MzU0MDIsImV4cCI6MjA3MTQxMTQwMn0.fnQQD3YBWKSOgE9zSGcWPUBy1mx4621ep4DZ37ysj7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});